spec_version: 2 

environment:
  environment_name: params-shell
  state: inactive
  owner_email: johnathan.v@quali.com
  spaces:
  - Vido

inputs:
  agent:
    type: agent
    default: review1-vido

grains:
  shell:
    kind: blueprint
    spec:
      source:
        store: bps
        path: blueprints/shell-print-params.yaml
      inputs:
      - agent: '{{ .inputs.agent }}'

  helloworld:
    kind: terraform
    spec:
      source:
        store: bps
        path: terraform/hello-world-source
      agent:
        name: '{{.inputs.agent}}'

