# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "vidos-amazing-bucket"
    encrypt = false
    key     = "staging/hello-world-remote/terraform.tfstate"
    region  = "eu-west-1"
  }
}
